### ISSUE TITLE
感谢大佬分享！

### ISSUE THREAD

**Issue by 1357310795** [Seekladoom/Seekladoom-ASS-Effect#1]
真心希望大佬能出一个ASS自动化的教程，网上可参考的资料实在太少了

**Comment by Seekladoom** [comment]
自动化特效的图文教程的话，你参考这个这个吧：
http://bbs.vcb-s.com/thread-4170-1-1.html

视频教程我也托朋友做了，你可以看看这位的B站视频教程：
https://space.bilibili.com/346816900/channel/detail?cid=81879
